import { z } from "zod";

export const StatusEnum = z.enum([
    "new", "working", "paused", "blocked", "suspended", "completed", "validate", "archivied"
]);

export const ActionEnum = z.enum([
    "create", "read", "update", "delete", "list"
]);


/**
 * Global DB Schema (Previously BaseSchema)
 * Root definition for any entity interacting with the global database.
 */
export const DbSchema = z.object({
    // UID generated by backend (or Auth UID for users/orgs)
    id: z.string().optional(),
    // Organization bounds
    orgId: z.string().readonly().default("PUBLIC"),
    ownId: z.string().optional(),
    // Core identity strings fallback when no Metadata translations are used
    name: z.string().optional(),
    description: z.string().optional(),
    // Categorization and states
    type: z.string().optional(),
    code: z.string().optional(),
    status: StatusEnum.default("new"),
    active: z.boolean().default(true),
    // version defaults to 1 on creation, but can accept FieldValue.increment(1) during backend updates
    version: z.union([z.number().int(), z.any()]).default(1),
    // Visibility
    public: z.boolean().default(true),
    // Traceability timestamps
    createdAt: z.date().optional(),
    createdBy: z.string().optional(),
    updatedAt: z.date().optional(),
    updatedBy: z.string().optional(),
    deletedAt: z.date().nullable().optional(),
    deletedBy: z.string().nullable().optional(),
    // Archiving
    isArchived: z.boolean().default(false),
    endLifeTime: z.date().nullable().optional(),
});

export type DbEntity = z.infer<typeof DbSchema>;

/**
 * Generative Correlation Schema
 * Written automatically via choreography to /users/[userId]/auths/[authId]
 */
export const CorelateSchema = z.object({
    authId: z.string(),
    linkedAt: z.date(),
    platform: z.string().optional()
});
export type Corelate = z.infer<typeof CorelateSchema>;
/**
 * Localized String Schema
 * Schema per i campi testuali multi-lingua.
 * L'italiano ("it") è considerato la lingua principale ed è obbligatorio (o fallback su EN).
 * "en" e "es" sono opzionali.
 */
export const LocalizedStringSchema = z.object({
    it: z.string().optional(),
    es: z.string().optional()
});
// La vecchia dichiarazione export type LocalizedStringera presente al fondo di base.ts. 
export type LocalizedString = z.infer<typeof LocalizedStringSchema>;

/**
 * Universal Node Schemas for Subcollections
 */
export const ProcessNodeSchema = DbSchema.merge(z.object({
    processId: z.string(),
    quantity: z.number().default(1),
    duration: z.number().optional()
}));
export type ProcessNode = z.infer<typeof ProcessNodeSchema>;

/**
 * API RBAC Schema Generators (Livello Controller)
 * Astrazioni riutilizzabili per creare automaticamente i payload di
 * Creazione, Aggiornamento, e Risposta di ogni Master Schema.
 */
// Campi Protetti (Inamovibili via API di Input)
export const ProtectedSystemFields = {
    id: true,
    orgId: true,
    code: true,
    ownId: true,
    users: true,
    updates: true,
    version: true,
    createdAt: true,
    createdBy: true,
    updatedAt: true,
    updatedBy: true,
    deletedAt: true,
    deletedBy: true,
    isArchived: true,
    endLifeTime: true,
} as const;
// Paginazione Standard (GET)
export const PaginationQuerySchema = z.object({
    limit: z.coerce.number().int().min(1).max(100).default(20),
    offset: z.coerce.number().int().min(0).default(0),
    cursor: z.string().optional(),
    orderBy: z.string().optional(),
    orderDirection: z.enum(['asc', 'desc']).default('desc'),
});
// Generatori Dinamici (Typescript + Zod Factory)
/** Genera lo schema per la creazione omettendo automaticamente i system fields */
export function createCreationSchema<T extends z.ZodObject<z.ZodRawShape>>(schema: T) {
    return schema.omit(ProtectedSystemFields);
}
/** Genera lo schema per l'aggiornamento (tutto opzionale, no system fields) */
export function createUpdateSchema<T extends z.ZodObject<z.ZodRawShape>>(schema: T) {
    return schema.omit(ProtectedSystemFields).partial();
}
/** Genera la risposta standard API per il Master Schema richiesto */
export function createResponseSchema<T extends z.ZodTypeAny>(schema: T) {
    return z.object({
        data: z.array(schema),
        meta: z.object({
            totalCount: z.number().int().optional(),
            nextCursor: z.string().optional(),
        }).optional(),
    });
}
