import { DbSchema } from "./db";
import { z } from "zod";

export const VectorSchema = z.object({
  embedding: z.array(z.number()).describe("The dense vector array generated by the embedding model"),
  model: z.string().describe("The name of the embedding model used (e.g. text-embedding-004)"),
  tokens: z.number().optional().describe("Number of tokens consumed to generate this vector"),
  inputHash: z.string().optional().describe("Hash of the input text to track if embedding needs regeneration"),
  updatedAt: z.number().describe("Timestamp of when this vector was generated"),
});

export type Vector = z.infer<typeof VectorSchema>;

export const VectorDbSchema = DbSchema.merge(VectorSchema);
export type VectorDbEntity = z.infer<typeof VectorDbSchema>;
